-- ============================================================
-- STEP 3: Remaining Tables (26-101) with RLS
-- ============================================================

-- WhatsApp settings policy
DO $$ BEGIN CREATE POLICY "whatsapp_settings_select" ON public.whatsapp_settings FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "whatsapp_settings_manage" ON public.whatsapp_settings FOR ALL USING (company_id = get_user_company_id() AND (has_company_role(auth.uid(), 'owner') OR has_company_role(auth.uid(), 'admin'))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- eCommerce
CREATE TABLE IF NOT EXISTS public.ecommerce_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), external_order_id TEXT, external_source TEXT, status TEXT DEFAULT 'pending', total_amount NUMERIC, currency TEXT DEFAULT 'SAR', items JSONB, shipping_address JSONB, billing_address JSONB, payment_method TEXT, payment_status TEXT DEFAULT 'pending', tracking_number TEXT, carrier TEXT, estimated_delivery TIMESTAMPTZ, delivered_at TIMESTAMPTZ, notes TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.ecommerce_returns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, order_id UUID REFERENCES public.ecommerce_orders(id), customer_id UUID REFERENCES public.customers(id), return_number TEXT, reason TEXT, reason_category TEXT, description TEXT, status TEXT DEFAULT 'pending', refund_amount NUMERIC, refund_status TEXT DEFAULT 'pending', refunded_at TIMESTAMPTZ, approved_by UUID, approved_at TIMESTAMPTZ, photos TEXT[], created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Real Estate
CREATE TABLE IF NOT EXISTS public.properties (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, title TEXT NOT NULL, title_en TEXT, description TEXT, property_type TEXT, status TEXT DEFAULT 'available', price NUMERIC, price_type TEXT, currency TEXT DEFAULT 'SAR', city TEXT, district TEXT, address TEXT, area_sqm NUMERIC, bedrooms INTEGER, bathrooms INTEGER, amenities TEXT[], images TEXT[], location JSONB, owner_id UUID, manager_id UUID, external_id TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.property_viewings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, property_id UUID REFERENCES public.properties(id), customer_id UUID REFERENCES public.customers(id), scheduled_at TIMESTAMPTZ, status TEXT DEFAULT 'scheduled', assigned_to UUID, duration_minutes INTEGER DEFAULT 30, notes TEXT, feedback TEXT, rating INTEGER, confirmed_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, cancellation_reason TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Healthcare
CREATE TABLE IF NOT EXISTS public.healthcare_appointments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), doctor_name TEXT, doctor_name_ar TEXT, department TEXT, appointment_type TEXT, scheduled_at TIMESTAMPTZ, duration_minutes INTEGER DEFAULT 30, status TEXT DEFAULT 'scheduled', notes TEXT, diagnosis TEXT, prescription TEXT, follow_up_date TIMESTAMPTZ, insurance_number TEXT, insurance_provider TEXT, is_urgent BOOLEAN DEFAULT false, confirmed_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, cancellation_reason TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Restaurant
CREATE TABLE IF NOT EXISTS public.restaurant_reservations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), reservation_number TEXT, party_size INTEGER NOT NULL, scheduled_at TIMESTAMPTZ NOT NULL, duration_minutes INTEGER DEFAULT 90, table_number TEXT, status TEXT DEFAULT 'pending', special_requests TEXT, occasion TEXT, dietary_restrictions TEXT[], reminder_sent BOOLEAN DEFAULT false, no_show BOOLEAN DEFAULT false, confirmed_at TIMESTAMPTZ, seated_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, cancellation_reason TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.restaurant_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), reservation_id UUID REFERENCES public.restaurant_reservations(id), order_number TEXT, order_type TEXT DEFAULT 'delivery', status TEXT DEFAULT 'pending', items JSONB, subtotal NUMERIC, tax NUMERIC, discount NUMERIC DEFAULT 0, delivery_fee NUMERIC DEFAULT 0, total_amount NUMERIC, currency TEXT DEFAULT 'SAR', payment_method TEXT, payment_status TEXT DEFAULT 'pending', delivery_address JSONB, delivery_instructions TEXT, estimated_ready TIMESTAMPTZ, estimated_delivery TIMESTAMPTZ, prepared_at TIMESTAMPTZ, picked_up_at TIMESTAMPTZ, delivered_at TIMESTAMPTZ, driver_id UUID, driver_name TEXT, driver_phone TEXT, rating INTEGER, feedback TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Education
CREATE TABLE IF NOT EXISTS public.education_courses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, title TEXT NOT NULL, title_ar TEXT, description TEXT, description_ar TEXT, course_code TEXT, instructor_name TEXT, instructor_name_ar TEXT, start_date TIMESTAMPTZ, end_date TIMESTAMPTZ, duration_hours INTEGER, max_participants INTEGER, current_participants INTEGER DEFAULT 0, price NUMERIC, currency TEXT DEFAULT 'SAR', location TEXT, is_online BOOLEAN DEFAULT false, meeting_link TEXT, schedule JSONB, status TEXT DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.education_enrollments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, course_id UUID REFERENCES public.education_courses(id), customer_id UUID REFERENCES public.customers(id), enrollment_number TEXT, status TEXT DEFAULT 'enrolled', enrolled_at TIMESTAMPTZ DEFAULT now(), completed_at TIMESTAMPTZ, progress_percentage INTEGER DEFAULT 0, payment_status TEXT DEFAULT 'pending', payment_amount NUMERIC, certificate_issued BOOLEAN DEFAULT false, certificate_url TEXT, notes TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Financial
CREATE TABLE IF NOT EXISTS public.financial_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), request_number TEXT, request_type TEXT NOT NULL, amount NUMERIC, currency TEXT DEFAULT 'SAR', status TEXT DEFAULT 'pending', description TEXT, documents JSONB, assigned_to UUID, approved_by UUID, approved_at TIMESTAMPTZ, rejected_at TIMESTAMPTZ, rejection_reason TEXT, completed_at TIMESTAMPTZ, notes TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.financial_consultations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), consultation_number TEXT, consultation_type TEXT NOT NULL, topic TEXT, advisor_id UUID, advisor_name TEXT, scheduled_at TIMESTAMPTZ, duration_minutes INTEGER DEFAULT 60, meeting_link TEXT, status TEXT DEFAULT 'scheduled', notes TEXT, customer_rating INTEGER, customer_feedback TEXT, completed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, cancellation_reason TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Maintenance
CREATE TABLE IF NOT EXISTS public.maintenance_tickets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), property_id UUID REFERENCES public.properties(id), ticket_number TEXT, title TEXT, description TEXT, category TEXT, subcategory TEXT, priority TEXT DEFAULT 'medium', urgency TEXT, status TEXT DEFAULT 'open', assigned_to UUID, assigned_at TIMESTAMPTZ, scheduled_at TIMESTAMPTZ, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, estimated_cost NUMERIC, approved_cost NUMERIC, actual_cost NUMERIC, requires_approval BOOLEAN DEFAULT false, approved_by UUID, approved_at TIMESTAMPTZ, resolution TEXT, photos TEXT[], customer_rating INTEGER, customer_feedback TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Marketing
CREATE TABLE IF NOT EXISTS public.marketing_campaigns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, campaign_type TEXT NOT NULL DEFAULT 'general', status TEXT NOT NULL DEFAULT 'draft', budget NUMERIC, start_date TIMESTAMPTZ, end_date TIMESTAMPTZ, target_audience JSONB, target_regions TEXT[], created_by UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.campaign_analytics (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id UUID NOT NULL REFERENCES public.marketing_campaigns(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, date DATE NOT NULL DEFAULT CURRENT_DATE, impressions INTEGER DEFAULT 0, clicks INTEGER DEFAULT 0, conversions INTEGER DEFAULT 0, messages_sent INTEGER DEFAULT 0, messages_opened INTEGER DEFAULT 0, leads_generated INTEGER DEFAULT 0, cost_spent NUMERIC DEFAULT 0, revenue_generated NUMERIC DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(campaign_id, date));

-- WhatsApp Campaigns
CREATE TABLE IF NOT EXISTS public.whatsapp_campaigns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT, template_id UUID, template_name TEXT, template_language TEXT DEFAULT 'ar', message_text TEXT, media_url TEXT, status TEXT NOT NULL DEFAULT 'draft', scheduled_at TIMESTAMPTZ, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, total_recipients INTEGER DEFAULT 0, sent_count INTEGER DEFAULT 0, delivered_count INTEGER DEFAULT 0, read_count INTEGER DEFAULT 0, failed_count INTEGER DEFAULT 0, target_filter JSONB, created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.campaign_recipients (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), campaign_id UUID NOT NULL REFERENCES public.whatsapp_campaigns(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), customer_name TEXT, phone TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', sent_at TIMESTAMPTZ, delivered_at TIMESTAMPTZ, read_at TIMESTAMPTZ, error_message TEXT, whatsapp_message_id TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.whatsapp_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, language TEXT DEFAULT 'ar', category TEXT DEFAULT 'MARKETING', status TEXT DEFAULT 'draft', header_type TEXT, header_content TEXT, body_text TEXT NOT NULL, footer_text TEXT, buttons JSONB, variables JSONB, whatsapp_template_id TEXT, submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, rejected_at TIMESTAMPTZ, rejection_reason TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.automated_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, trigger_type TEXT NOT NULL DEFAULT 'manual', trigger_event TEXT, trigger_value INTEGER, message_text TEXT NOT NULL, template_id UUID REFERENCES public.whatsapp_templates(id), target_audience TEXT, target_filter JSONB, is_active BOOLEAN DEFAULT true, sent_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.automated_message_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, automated_message_id UUID REFERENCES public.automated_messages(id), customer_id UUID REFERENCES public.customers(id), customer_phone TEXT, customer_name TEXT, message_text TEXT, status TEXT DEFAULT 'pending', sent_at TIMESTAMPTZ DEFAULT now(), error_message TEXT);

-- Tags & Sentiment
CREATE TABLE IF NOT EXISTS public.conversation_tags (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, name_ar TEXT, color TEXT NOT NULL DEFAULT '#3B82F6', description TEXT, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.conversation_tag_assignments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE, tag_id UUID NOT NULL REFERENCES public.conversation_tags(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, assigned_by UUID, assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(conversation_id, tag_id));
CREATE TABLE IF NOT EXISTS public.conversation_sentiment_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE, message_id UUID REFERENCES public.messages(id), sentiment TEXT NOT NULL, sentiment_score NUMERIC, keywords TEXT[], detected_issues TEXT[], requires_escalation BOOLEAN DEFAULT false, escalation_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.conversation_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, auto_close_enabled BOOLEAN DEFAULT false, auto_close_hours INTEGER DEFAULT 48, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Customer extras
CREATE TABLE IF NOT EXISTS public.customer_profiles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, behavioral_type TEXT, personality_type TEXT, preferred_communication_style TEXT, preferred_language TEXT, current_emotion TEXT, journey_stage TEXT, trust_level INTEGER DEFAULT 50, purchase_probability NUMERIC, churn_risk NUMERIC, lifetime_value NUMERIC, average_order_value NUMERIC, total_orders INTEGER DEFAULT 0, total_returns INTEGER DEFAULT 0, total_complaints INTEGER DEFAULT 0, detected_interests TEXT[], detected_pain_points TEXT[], best_persuasion_strategy TEXT, ai_summary TEXT, last_positive_interaction TIMESTAMPTZ, last_negative_interaction TIMESTAMPTZ, last_analysis_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(customer_id, company_id));
CREATE TABLE IF NOT EXISTS public.customer_analysis_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), customer_profile_id UUID NOT NULL REFERENCES public.customer_profiles(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), detected_intent TEXT, detected_emotion TEXT, sentiment_score NUMERIC, persuasion_attempt TEXT, persuasion_success BOOLEAN, analysis_context JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.customer_appointments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), title TEXT NOT NULL, description TEXT, scheduled_at TIMESTAMPTZ NOT NULL, duration_minutes INTEGER DEFAULT 30, location TEXT, status TEXT DEFAULT 'scheduled', reminder_type TEXT DEFAULT 'whatsapp', reminder_sent BOOLEAN DEFAULT false, reminder_sent_at TIMESTAMPTZ, created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.customer_internal_notes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE, content TEXT NOT NULL, created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.quick_replies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, title TEXT NOT NULL, content TEXT NOT NULL, shortcut TEXT, category TEXT, created_by UUID, usage_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());

-- Support tickets
CREATE TABLE IF NOT EXISTS public.support_tickets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, customer_id UUID REFERENCES public.customers(id), ticket_number TEXT, subject TEXT NOT NULL, description TEXT, category TEXT, priority TEXT DEFAULT 'medium', status TEXT DEFAULT 'open', assigned_to UUID, sla_deadline TIMESTAMPTZ, first_response_at TIMESTAMPTZ, resolved_at TIMESTAMPTZ, closed_at TIMESTAMPTZ, satisfaction_rating INTEGER, satisfaction_comment TEXT, tags TEXT[], metadata JSONB, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.ticket_responses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id UUID NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, responder_id UUID, responder_name TEXT, response_type TEXT DEFAULT 'reply', content TEXT NOT NULL, is_internal BOOLEAN DEFAULT false, attachments JSONB, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.ticket_ai_analysis (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id UUID NOT NULL UNIQUE REFERENCES public.support_tickets(id) ON DELETE CASCADE, company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, detected_category TEXT, detected_priority TEXT, sentiment TEXT, sentiment_score NUMERIC, suggested_response TEXT, suggested_assignee UUID, keywords TEXT[], similar_tickets JSONB, auto_categorized BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Company settings
CREATE TABLE IF NOT EXISTS public.company_info (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, description TEXT, description_ar TEXT, phone TEXT, email TEXT, website TEXT, address TEXT, address_ar TEXT, working_hours JSONB, services JSONB, prices JSONB, policies JSONB, locations JSONB, team_members JSONB, custom_fields JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.company_marketing_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, industry_type TEXT NOT NULL DEFAULT 'general', quick_descriptions JSONB NOT NULL DEFAULT '[]', targeting_categories JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.company_ui_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, hidden_sections TEXT[], hidden_settings_tabs TEXT[], hidden_ai_hub_tabs TEXT[], custom_labels JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.custom_ui_sections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, section_id TEXT NOT NULL, section_name TEXT NOT NULL, section_name_ar TEXT NOT NULL, section_type TEXT NOT NULL DEFAULT 'custom', parent_section TEXT, icon TEXT, description TEXT, config JSONB, is_active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id, section_id, parent_section));
CREATE TABLE IF NOT EXISTS public.company_usage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, current_users INTEGER NOT NULL DEFAULT 0, monthly_conversations INTEGER NOT NULL DEFAULT 0, current_storage_bytes BIGINT NOT NULL DEFAULT 0, last_conversation_reset TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.company_twilio_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, twilio_account_sid TEXT NOT NULL, twilio_auth_token TEXT NOT NULL, whatsapp_number TEXT, phone_number_sid TEXT, status TEXT DEFAULT 'active', card_linked_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.dashboard_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, background_type TEXT DEFAULT 'color', background_color TEXT, background_image_url TEXT, overlay_opacity NUMERIC DEFAULT 0.5, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.alert_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, alert_type TEXT NOT NULL, is_enabled BOOLEAN DEFAULT true, threshold_value INTEGER, threshold_period_minutes INTEGER, notification_channels JSONB DEFAULT '["dashboard"]', notification_emails TEXT[], notification_phones TEXT[], created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(company_id, alert_type));
CREATE TABLE IF NOT EXISTS public.alert_notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, alert_type TEXT NOT NULL, severity TEXT NOT NULL, message TEXT NOT NULL, details JSONB, sent_via TEXT[], acknowledged BOOLEAN DEFAULT false, acknowledged_at TIMESTAMPTZ, acknowledged_by UUID, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.system_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, log_type TEXT NOT NULL, severity TEXT NOT NULL DEFAULT 'info', source TEXT NOT NULL, message TEXT NOT NULL, details JSONB, response_time_ms INTEGER, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.team_invitations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, email TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'agent', department_id UUID REFERENCES public.departments(id), invited_by UUID NOT NULL, token TEXT NOT NULL UNIQUE DEFAULT gen_random_uuid()::text, status TEXT NOT NULL DEFAULT 'pending', expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'), accepted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.subscription_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, plan_id UUID REFERENCES public.subscription_plans(id), action TEXT NOT NULL, amount NUMERIC, notes TEXT, created_by UUID, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.demo_requests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, company TEXT, company_size TEXT, industry TEXT, package TEXT, message TEXT, notes TEXT, status TEXT NOT NULL DEFAULT 'new', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());

-- eCommerce integrations
CREATE TABLE IF NOT EXISTS public.ecommerce_integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, platform_name TEXT NOT NULL, api_endpoint TEXT NOT NULL, api_key TEXT NOT NULL, store_url TEXT, is_active BOOLEAN DEFAULT true, sync_status TEXT, sync_error TEXT, products_count INTEGER DEFAULT 0, last_sync_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id, platform_name));
CREATE TABLE IF NOT EXISTS public.ecommerce_products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, integration_id UUID NOT NULL REFERENCES public.ecommerce_integrations(id) ON DELETE CASCADE, external_id TEXT NOT NULL, name TEXT NOT NULL, name_ar TEXT, description TEXT, description_ar TEXT, price NUMERIC, compare_at_price NUMERIC, currency TEXT DEFAULT 'SAR', sku TEXT, barcode TEXT, brand TEXT, vendor TEXT, category TEXT, category_ar TEXT, tags TEXT[], images TEXT[], quantity INTEGER, is_available BOOLEAN DEFAULT true, weight NUMERIC, weight_unit TEXT, options JSONB, variants JSONB, metadata JSONB, product_url TEXT, synced_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id, integration_id, external_id));
CREATE TABLE IF NOT EXISTS public.erp_integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, integration_name TEXT NOT NULL, api_endpoint TEXT NOT NULL, api_key TEXT NOT NULL, is_active BOOLEAN DEFAULT true, last_sync_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(company_id, integration_name));

-- Marketing intelligence
CREATE TABLE IF NOT EXISTS public.marketing_decisions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, campaign_id UUID REFERENCES public.marketing_campaigns(id), title TEXT NOT NULL, name TEXT, description TEXT, decision_type TEXT NOT NULL, guidance_level TEXT, priority TEXT DEFAULT 'medium', status TEXT NOT NULL DEFAULT 'pending', is_active BOOLEAN DEFAULT true, ai_reasoning TEXT, confidence_score NUMERIC, expected_impact JSONB, actual_results JSONB, target_regions TEXT[], custom_message TEXT, start_date TIMESTAMPTZ, end_date TIMESTAMPTZ, impressions_count INTEGER DEFAULT 0, conversions_count INTEGER DEFAULT 0, approved_by UUID, approved_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.marketing_decision_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, decision_id UUID REFERENCES public.marketing_decisions(id), conversation_id UUID REFERENCES public.conversations(id), customer_id UUID REFERENCES public.customers(id), ai_run_id UUID REFERENCES public.ai_runs(id), decision_type TEXT, guidance_level TEXT, message_sent TEXT, customer_response TEXT, converted BOOLEAN DEFAULT false, converted_at TIMESTAMPTZ, conversion_value NUMERIC, notes TEXT, applied_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.marketing_template_usage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, template_key TEXT NOT NULL, template_type TEXT, conversation_id UUID REFERENCES public.conversations(id), customer_id UUID REFERENCES public.customers(id), message_sent TEXT, sent_at TIMESTAMPTZ DEFAULT now(), conversion_status TEXT, conversion_value NUMERIC, converted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.persuasion_tracking (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), customer_id UUID REFERENCES public.customers(id), strategy_used TEXT, message_sent TEXT, customer_response TEXT, was_successful BOOLEAN, conversion_value NUMERIC, emotion_before TEXT, emotion_after TEXT, notes TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sales_scenario_tracking (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), customer_id UUID REFERENCES public.customers(id), scenario_type TEXT NOT NULL, scenario_key TEXT, trigger_condition TEXT, message_sent TEXT, outcome TEXT, outcome_at TIMESTAMPTZ, revenue_generated NUMERIC, products_offered TEXT[], discount_offered NUMERIC, notes TEXT, triggered_at TIMESTAMPTZ DEFAULT now());

-- Global learning
CREATE TABLE IF NOT EXISTS public.global_learned_patterns (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), pattern_type TEXT NOT NULL, sector TEXT NOT NULL, pattern_key TEXT NOT NULL, pattern_data JSONB DEFAULT '{}', success_rate NUMERIC DEFAULT 0, usage_count INTEGER DEFAULT 0, contributing_companies INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, quality_score NUMERIC DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(pattern_type, sector, pattern_key));
CREATE TABLE IF NOT EXISTS public.company_pattern_contributions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, pattern_id UUID REFERENCES public.global_learned_patterns(id) ON DELETE CASCADE, local_usage_count INTEGER DEFAULT 0, local_success_rate NUMERIC DEFAULT 0, contribution_weight NUMERIC DEFAULT 1, last_synced_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(company_id, pattern_id));
CREATE TABLE IF NOT EXISTS public.discovered_faqs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sector TEXT NOT NULL, question_pattern TEXT NOT NULL, question_variations JSONB, best_answer TEXT, answer_variations JSONB, frequency_score NUMERIC DEFAULT 0, quality_score NUMERIC DEFAULT 0, contributing_companies INTEGER DEFAULT 0, is_verified BOOLEAN DEFAULT false, auto_added_to_kb BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.prompt_optimizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sector TEXT NOT NULL, optimization_type TEXT NOT NULL, original_prompt TEXT, optimized_prompt TEXT, improvement_metric NUMERIC DEFAULT 0, test_count INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.successful_responses_pool (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sector TEXT NOT NULL, intent TEXT, customer_stage TEXT, customer_emotion TEXT, original_message TEXT, successful_response TEXT NOT NULL, success_indicator TEXT, quality_score NUMERIC DEFAULT 0, usage_count INTEGER DEFAULT 0, contributing_companies INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.successful_persuasion_strategies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sector TEXT NOT NULL, strategy_name TEXT NOT NULL, strategy_description TEXT, customer_stage TEXT, customer_emotion TEXT, total_attempts INTEGER DEFAULT 0, total_successes INTEGER DEFAULT 0, avg_conversion_rate NUMERIC DEFAULT 0, example_messages JSONB, contributing_companies INTEGER DEFAULT 0, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.learning_analytics (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, period_start DATE NOT NULL, period_end DATE NOT NULL, total_interactions INTEGER DEFAULT 0, successful_responses INTEGER DEFAULT 0, modified_responses INTEGER DEFAULT 0, rejected_responses INTEGER DEFAULT 0, avg_response_quality NUMERIC DEFAULT 0, patterns_contributed INTEGER DEFAULT 0, patterns_benefited_from INTEGER DEFAULT 0, improvement_vs_previous NUMERIC DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(company_id, period_start, period_end));

-- Sector templates
CREATE TABLE IF NOT EXISTS public.sector_marketing_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, industry_type TEXT NOT NULL, template_key TEXT NOT NULL, template_type TEXT NOT NULL, title TEXT NOT NULL, title_ar TEXT, content TEXT NOT NULL, content_ar TEXT, variables JSONB, is_active BOOLEAN DEFAULT true, usage_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sector_quick_replies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, industry_type TEXT NOT NULL, shortcut TEXT NOT NULL, category TEXT NOT NULL, content TEXT NOT NULL, content_ar TEXT, is_active BOOLEAN DEFAULT true, usage_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.sector_sales_scenarios (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE, industry_type TEXT NOT NULL, scenario_key TEXT NOT NULL, scenario_type TEXT NOT NULL, title TEXT NOT NULL, title_ar TEXT, trigger_condition TEXT, response_template TEXT NOT NULL, response_template_ar TEXT, success_indicators JSONB, is_active BOOLEAN DEFAULT true, usage_count INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Social
CREATE TABLE IF NOT EXISTS public.social_channels (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, channel_type TEXT NOT NULL, channel_name TEXT NOT NULL, account_id TEXT, page_id TEXT, access_token TEXT, refresh_token TEXT, token_expires_at TIMESTAMPTZ, config JSONB, is_active BOOLEAN DEFAULT true, last_sync_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now(), UNIQUE(company_id, channel_type, account_id));
CREATE TABLE IF NOT EXISTS public.social_channel_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, channel_id UUID NOT NULL REFERENCES public.social_channels(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), external_message_id TEXT, direction TEXT NOT NULL, content TEXT, media_url TEXT, message_type TEXT DEFAULT 'text', sender_id TEXT, sender_name TEXT, status TEXT DEFAULT 'sent', metadata JSONB, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.scheduled_posts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, channel_id UUID REFERENCES public.social_channels(id), content TEXT NOT NULL, media_urls TEXT[], scheduled_at TIMESTAMPTZ NOT NULL, status TEXT DEFAULT 'scheduled', published_at TIMESTAMPTZ, error_message TEXT, ai_generated BOOLEAN DEFAULT false, created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

-- Media
CREATE TABLE IF NOT EXISTS public.media_folders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, name TEXT NOT NULL, parent_id UUID REFERENCES public.media_folders(id), created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.media_files (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, folder_id UUID REFERENCES public.media_folders(id), name TEXT NOT NULL, file_url TEXT NOT NULL, file_type TEXT NOT NULL, file_size BIGINT DEFAULT 0, mime_type TEXT, thumbnail_url TEXT, alt_text TEXT, tags TEXT[], metadata JSONB, uploaded_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.media_ai_settings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, auto_tag BOOLEAN DEFAULT true, auto_alt_text BOOLEAN DEFAULT true, auto_categorize BOOLEAN DEFAULT true, preferred_model TEXT DEFAULT 'google/gemini-2.5-flash', created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.media_usage_log (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, media_file_id UUID REFERENCES public.media_files(id), used_in TEXT, used_by UUID, context TEXT, created_at TIMESTAMPTZ DEFAULT now());

-- Misc
CREATE TABLE IF NOT EXISTS public.unanswered_questions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, conversation_id UUID REFERENCES public.conversations(id), question TEXT NOT NULL, customer_id UUID REFERENCES public.customers(id), times_asked INTEGER DEFAULT 1, status TEXT DEFAULT 'pending', suggested_answer TEXT, added_to_kb BOOLEAN DEFAULT false, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.landing_pages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, content JSONB DEFAULT '{}', meta_tags JSONB DEFAULT '{}', is_active BOOLEAN DEFAULT true, published_at TIMESTAMPTZ, created_by UUID, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.landing_page_leads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), landing_page_id UUID REFERENCES public.landing_pages(id), name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, company_name TEXT, company_size TEXT, industry TEXT, package_interest TEXT, message TEXT, source TEXT, utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, status TEXT DEFAULT 'new', notes TEXT, assigned_to UUID, converted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.lead_activities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), lead_id UUID NOT NULL REFERENCES public.landing_page_leads(id) ON DELETE CASCADE, activity_type TEXT NOT NULL, description TEXT, notes TEXT, outcome TEXT, user_id UUID, user_name TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.visitor_sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), visitor_id TEXT, page_url TEXT, referrer TEXT, utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, device_type TEXT, browser TEXT, os TEXT, country TEXT, city TEXT, ip_address TEXT, session_duration INTEGER DEFAULT 0, pages_viewed INTEGER DEFAULT 1, bounce BOOLEAN DEFAULT false, converted BOOLEAN DEFAULT false, conversion_type TEXT, started_at TIMESTAMPTZ DEFAULT now(), ended_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.page_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), session_id UUID REFERENCES public.visitor_sessions(id), event_type TEXT NOT NULL, event_name TEXT, element_id TEXT, element_text TEXT, page_url TEXT, scroll_depth INTEGER, metadata JSONB, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS public.section_engagement (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), session_id UUID REFERENCES public.visitor_sessions(id), section_name TEXT NOT NULL, time_spent_seconds INTEGER DEFAULT 0, scroll_in_percent NUMERIC, scroll_out_percent NUMERIC, interactions_count INTEGER DEFAULT 0, is_visible BOOLEAN DEFAULT true, first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());

-- Enable RLS on all new tables
ALTER TABLE public.ecommerce_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecommerce_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_viewings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.healthcare_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automated_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automated_message_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_tag_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_sentiment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_analysis_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_internal_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quick_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_ai_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_info ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_marketing_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_ui_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_ui_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_twilio_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alert_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demo_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecommerce_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ecommerce_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.erp_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_decisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_decision_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_template_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.persuasion_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_scenario_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.global_learned_patterns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_pattern_contributions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discovered_faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_optimizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.successful_responses_pool ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.successful_persuasion_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.learning_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sector_marketing_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sector_quick_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sector_sales_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_channel_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_ai_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_usage_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unanswered_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.landing_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.landing_page_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.section_engagement ENABLE ROW LEVEL SECURITY;

-- RLS policies for all remaining tables (company-scoped standard pattern)
DO $$ BEGIN CREATE POLICY "ecommerce_orders_select" ON public.ecommerce_orders FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "ecommerce_orders_insert" ON public.ecommerce_orders FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "ecommerce_orders_update" ON public.ecommerce_orders FOR UPDATE USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "ecommerce_returns_select" ON public.ecommerce_returns FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "ecommerce_returns_insert" ON public.ecommerce_returns FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "properties_select" ON public.properties FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "properties_insert" ON public.properties FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "viewings_select" ON public.property_viewings FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "viewings_insert" ON public.property_viewings FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "healthcare_select" ON public.healthcare_appointments FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "healthcare_insert" ON public.healthcare_appointments FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "reservations_select" ON public.restaurant_reservations FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "reservations_insert" ON public.restaurant_reservations FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "restaurant_orders_select" ON public.restaurant_orders FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "restaurant_orders_insert" ON public.restaurant_orders FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "maintenance_select" ON public.maintenance_tickets FOR SELECT USING (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "maintenance_insert" ON public.maintenance_tickets FOR INSERT WITH CHECK (company_id = get_user_company_id() OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view courses in their company" ON public.education_courses FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage courses in their company" ON public.education_courses FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view enrollments in their company" ON public.education_enrollments FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage enrollments in their company" ON public.education_enrollments FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view financial requests in their company" ON public.financial_requests FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage financial requests in their company" ON public.financial_requests FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view consultations in their company" ON public.financial_consultations FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage consultations in their company" ON public.financial_consultations FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company campaigns" ON public.marketing_campaigns FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert campaigns" ON public.marketing_campaigns FOR INSERT WITH CHECK (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can update their campaigns" ON public.marketing_campaigns FOR UPDATE USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company analytics" ON public.campaign_analytics FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert analytics" ON public.campaign_analytics FOR INSERT WITH CHECK (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company WA campaigns" ON public.whatsapp_campaigns FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company WA campaigns" ON public.whatsapp_campaigns FOR ALL USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company WA templates" ON public.whatsapp_templates FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company WA templates" ON public.whatsapp_templates FOR ALL USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view campaign recipients" ON public.campaign_recipients FOR SELECT USING (campaign_id IN (SELECT id FROM whatsapp_campaigns WHERE company_id = get_user_company_id())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company automated messages" ON public.automated_messages FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company automated messages" ON public.automated_messages FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company message logs" ON public.automated_message_logs FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company tags" ON public.conversation_tags FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company tag assignments" ON public.conversation_tag_assignments FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage tag assignments" ON public.conversation_tag_assignments FOR ALL USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company sentiment history" ON public.conversation_sentiment_history FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view company conversation settings" ON public.conversation_settings FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage company conversation settings" ON public.conversation_settings FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Companies can view their customer profiles" ON public.customer_profiles FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Companies can insert customer profiles" ON public.customer_profiles FOR INSERT WITH CHECK (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Companies can update their customer profiles" ON public.customer_profiles FOR UPDATE USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Companies can view their analysis history" ON public.customer_analysis_history FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Companies can insert analysis history" ON public.customer_analysis_history FOR INSERT WITH CHECK (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view company appointments" ON public.customer_appointments FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can create company appointments" ON public.customer_appointments FOR INSERT WITH CHECK (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company internal notes" ON public.customer_internal_notes FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company internal notes" ON public.customer_internal_notes FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view quick replies in their company" ON public.quick_replies FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can create quick replies in their company" ON public.quick_replies FOR INSERT WITH CHECK (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company tickets" ON public.support_tickets FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company tickets" ON public.support_tickets FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company ticket responses" ON public.ticket_responses FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company ticket responses" ON public.ticket_responses FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company ticket analysis" ON public.ticket_ai_analysis FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company ticket analysis" ON public.ticket_ai_analysis FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company info" ON public.company_info FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert their company info" ON public.company_info FOR INSERT WITH CHECK (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can update their company info" ON public.company_info FOR UPDATE USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company marketing settings" ON public.company_marketing_settings FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company UI settings" ON public.company_ui_settings FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view custom sections for their company" ON public.custom_ui_sections FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view own company usage" ON public.company_usage FOR SELECT TO authenticated USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company twilio account" ON public.company_twilio_accounts FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company dashboard settings" ON public.dashboard_settings FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert their company dashboard settings" ON public.dashboard_settings FOR INSERT WITH CHECK (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can update their company dashboard settings" ON public.dashboard_settings FOR UPDATE USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Company users can view their alert settings" ON public.alert_settings FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Company users can view their notifications" ON public.alert_notifications FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company logs" ON public.system_logs FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert company logs" ON public.system_logs FOR INSERT WITH CHECK (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company invitations" ON public.team_invitations FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company invitations" ON public.team_invitations FOR ALL USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company subscription history" ON public.subscription_history FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Anyone can submit demo requests" ON public.demo_requests FOR INSERT WITH CHECK (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Super admins can view all demo requests" ON public.demo_requests FOR SELECT USING (is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company ecommerce integrations" ON public.ecommerce_integrations FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company products" ON public.ecommerce_products FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company ERP integrations" ON public.erp_integrations FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company decisions" ON public.marketing_decisions FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert decisions" ON public.marketing_decisions FOR INSERT WITH CHECK (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company marketing decision events" ON public.marketing_decision_events FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company marketing template usage" ON public.marketing_template_usage FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company persuasion tracking" ON public.persuasion_tracking FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company sales scenario tracking" ON public.sales_scenario_tracking FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Anyone can read global patterns" ON public.global_learned_patterns FOR SELECT TO authenticated USING (is_active = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Company can view own contributions" ON public.company_pattern_contributions FOR SELECT TO authenticated USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Anyone can read discovered FAQs" ON public.discovered_faqs FOR SELECT TO authenticated USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Anyone can read active optimizations" ON public.prompt_optimizations FOR SELECT TO authenticated USING (is_active = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Company can view own analytics" ON public.learning_analytics FOR SELECT TO authenticated USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view sector marketing templates" ON public.sector_marketing_templates FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR company_id IS NULL); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view sector quick replies" ON public.sector_quick_replies FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR company_id IS NULL); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view sector sales scenarios" ON public.sector_sales_scenarios FOR SELECT USING (company_id = get_user_company_id(auth.uid()) OR company_id IS NULL); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company social channels" ON public.social_channels FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage their company social channels" ON public.social_channels FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company social messages" ON public.social_channel_messages FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view their company scheduled posts" ON public.scheduled_posts FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view media folders in their company" ON public.media_folders FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can create media folders in their company" ON public.media_folders FOR INSERT WITH CHECK (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view media files for their company" ON public.media_files FOR SELECT USING (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can insert media files for their company" ON public.media_files FOR INSERT WITH CHECK (company_id IN (SELECT company_id FROM company_users WHERE user_id = auth.uid() AND is_active = true)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view media AI settings in their company" ON public.media_ai_settings FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view media usage in their company" ON public.media_usage_log FOR SELECT USING (company_id = get_user_company_id()); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can view unanswered questions" ON public.unanswered_questions FOR SELECT USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Users can manage unanswered questions" ON public.unanswered_questions FOR ALL USING (company_id = get_user_company_id(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Public can view active landing pages" ON public.landing_pages FOR SELECT USING (is_active = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Public can submit leads" ON public.landing_page_leads FOR INSERT WITH CHECK (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Super admins can manage lead activities" ON public.lead_activities FOR ALL USING (is_super_admin(auth.uid())); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Public can create visitor sessions" ON public.visitor_sessions FOR INSERT WITH CHECK (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Public can create page events" ON public.page_events FOR INSERT WITH CHECK (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Public can create section engagement" ON public.section_engagement FOR INSERT WITH CHECK (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Successful responses read" ON public.successful_responses_pool FOR SELECT TO authenticated USING (is_active = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Persuasion strategies read" ON public.successful_persuasion_strategies FOR SELECT TO authenticated USING (is_active = true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;